package com.skyline.sms.caster.pojo;

// Generated 2015-10-16 10:42:03 by Hibernate Tools 4.3.1

import java.util.Date;

/**
 * TMessageSent generated by hbm2java
 */
public class TMessageSent implements java.io.Serializable {

	private Integer id;
	private Integer contactId;
	private String contactName;
	private Integer contactType;
	private String message;
	private String portName;
	private String portNumber;
	private Date sentDate;
	private Integer status;
	private Date createDate;
	private Date updateDate;
	private String number;
	private String subject;

	public TMessageSent() {
	}


	
	public TMessageSent( TMessage msg){
		contactId=msg.getContactId();
		contactName=msg.getContactName();
		contactType=msg.getContactType();
		number=msg.getNumber();
		message=msg.getMessage();
		subject=msg.getSubject();
		
	}
	
	
	public TMessageSent(int contactId, String contactName, int contactType,
			String message, String portName, Date sentDate, int status,
			Date createDate, Date updateDate, String number) {
		this.contactId = contactId;
		this.contactName = contactName;
		this.contactType = contactType;
		this.message = message;
		this.portName = portName;
		this.sentDate = sentDate;
		this.status = status;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.number = number;
	}

	public TMessageSent(Integer contactId, String contactName, Integer contactType,
			String message, String portName, String portNumber, Date sentDate,
			Integer status, Date createDate, Date updateDate, String number,
			String subject) {
		this.contactId = contactId;
		this.contactName = contactName;
		this.contactType = contactType;
		this.message = message;
		this.portName = portName;
		this.portNumber = portNumber;
		this.sentDate = sentDate;
		this.status = status;
		this.createDate = createDate;
		this.updateDate = updateDate;
		this.number = number;
		this.subject = subject;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public Integer getContactType() {
		return this.contactType;
	}

	public void setContactType(Integer contactType) {
		this.contactType = contactType;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getPortName() {
		return this.portName;
	}

	public void setPortName(String portName) {
		this.portName = portName;
	}

	public String getPortNumber() {
		return this.portNumber;
	}

	public void setPortNumber(String portNumber) {
		this.portNumber = portNumber;
	}

	public Date getSentDate() {
		return this.sentDate;
	}

	public void setSentDate(Date sentDate) {
		this.sentDate = sentDate;
	}

	public Integer getStatus() {
		return this.status;
	}

	public void setStatus(Integer status) {
		this.status = status;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

}
