package com.skyline.sms.caster.pojo;
// Generated 2015-9-30 11:50:52 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * TMessageSent generated by hbm2java
 */
public class TMessageSent implements java.io.Serializable {

	private Integer id;
	private int contactId;
	private String contactName;
	private int contactType;
	private String message;
	private String portName;
	private String portNumber;
	private Date sentDate;
	private int status;
	private Date createDate;
	private Date updateDate;

	public TMessageSent() {
	}

	public TMessageSent(int contactId, String contactName, int contactType, String message, String portName,
			Date sentDate, int status, Date createDate, Date updateDate) {
		this.contactId = contactId;
		this.contactName = contactName;
		this.contactType = contactType;
		this.message = message;
		this.portName = portName;
		this.sentDate = sentDate;
		this.status = status;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public TMessageSent(int contactId, String contactName, int contactType, String message, String portName,
			String portNumber, Date sentDate, int status, Date createDate, Date updateDate) {
		this.contactId = contactId;
		this.contactName = contactName;
		this.contactType = contactType;
		this.message = message;
		this.portName = portName;
		this.portNumber = portNumber;
		this.sentDate = sentDate;
		this.status = status;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public int getContactId() {
		return this.contactId;
	}

	public void setContactId(int contactId) {
		this.contactId = contactId;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public int getContactType() {
		return this.contactType;
	}

	public void setContactType(int contactType) {
		this.contactType = contactType;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getPortName() {
		return this.portName;
	}

	public void setPortName(String portName) {
		this.portName = portName;
	}

	public String getPortNumber() {
		return this.portNumber;
	}

	public void setPortNumber(String portNumber) {
		this.portNumber = portNumber;
	}

	public Date getSentDate() {
		return this.sentDate;
	}

	public void setSentDate(Date sentDate) {
		this.sentDate = sentDate;
	}

	public int getStatus() {
		return this.status;
	}

	public void setStatus(int status) {
		this.status = status;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
