package com.skyline.sms.caster.pojo;
// Generated 2015-9-30 11:50:52 by Hibernate Tools 4.0.0.Final

import java.util.Date;

/**
 * TMessageReceive generated by hbm2java
 */
public class TMessageReceive implements java.io.Serializable {

	private Integer id;
	private Integer contactId;
	private String contactName;
	private String contactNumber;
	private String message;
	private String portName;
	private String portNumber;
	private int replyStatus;
	private Date createDate;
	private Date updateDate;

	public TMessageReceive() {
	}

	public TMessageReceive(String contactNumber, String message, String portName, int replyStatus, Date createDate,
			Date updateDate) {
		this.contactNumber = contactNumber;
		this.message = message;
		this.portName = portName;
		this.replyStatus = replyStatus;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public TMessageReceive(Integer contactId, String contactName, String contactNumber, String message, String portName,
			String portNumber, int replyStatus, Date createDate, Date updateDate) {
		this.contactId = contactId;
		this.contactName = contactName;
		this.contactNumber = contactNumber;
		this.message = message;
		this.portName = portName;
		this.portNumber = portNumber;
		this.replyStatus = replyStatus;
		this.createDate = createDate;
		this.updateDate = updateDate;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public String getContactNumber() {
		return this.contactNumber;
	}

	public void setContactNumber(String contactNumber) {
		this.contactNumber = contactNumber;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getPortName() {
		return this.portName;
	}

	public void setPortName(String portName) {
		this.portName = portName;
	}

	public String getPortNumber() {
		return this.portNumber;
	}

	public void setPortNumber(String portNumber) {
		this.portNumber = portNumber;
	}

	public int getReplyStatus() {
		return this.replyStatus;
	}

	public void setReplyStatus(int replyStatus) {
		this.replyStatus = replyStatus;
	}

	public Date getCreateDate() {
		return this.createDate;
	}

	public void setCreateDate(Date createDate) {
		this.createDate = createDate;
	}

	public Date getUpdateDate() {
		return this.updateDate;
	}

	public void setUpdateDate(Date updateDate) {
		this.updateDate = updateDate;
	}

}
