package com.skyline.sms.caster.pojo;

// Generated 2015-10-16 10:42:03 by Hibernate Tools 4.3.1

/**
 * TMessage generated by hbm2java
 */
public class TMessage implements java.io.Serializable {

	private Integer id;
	private Integer contactId;
	private String contactName;
	private int contactType;
	private String message;
	private String portName;
	private String portNumber;
	private String number;
	private String subject;

	public TMessage() {
	}

	public TMessage(int contactType, String message, String number) {
		this.contactType = contactType;
		this.message = message;
		this.number = number;
	}

	public TMessage(Integer contactId, String contactName, int contactType,
			String message, String portName, String portNumber, String number,
			String subject) {
		this.contactId = contactId;
		this.contactName = contactName;
		this.contactType = contactType;
		this.message = message;
		this.portName = portName;
		this.portNumber = portNumber;
		this.number = number;
		this.subject = subject;
	}

	public Integer getId() {
		return this.id;
	}

	public void setId(Integer id) {
		this.id = id;
	}

	public Integer getContactId() {
		return this.contactId;
	}

	public void setContactId(Integer contactId) {
		this.contactId = contactId;
	}

	public String getContactName() {
		return this.contactName;
	}

	public void setContactName(String contactName) {
		this.contactName = contactName;
	}

	public int getContactType() {
		return this.contactType;
	}

	public void setContactType(int contactType) {
		this.contactType = contactType;
	}

	public String getMessage() {
		return this.message;
	}

	public void setMessage(String message) {
		this.message = message;
	}

	public String getPortName() {
		return this.portName;
	}

	public void setPortName(String portName) {
		this.portName = portName;
	}

	public String getPortNumber() {
		return this.portNumber;
	}

	public void setPortNumber(String portNumber) {
		this.portNumber = portNumber;
	}

	public String getNumber() {
		return this.number;
	}

	public void setNumber(String number) {
		this.number = number;
	}

	public String getSubject() {
		return this.subject;
	}

	public void setSubject(String subject) {
		this.subject = subject;
	}

}
